### PR TITLE
Optional transit line penalties when no explicit line was given

### PR DESCRIPTION
**Pull request by aheld84**
This relates to #18 

Currently, if no transit line is given, all edges get penalty factor 0
regardless of whether there are transit lines following the edge or not.
The change introduced in this commit will give penalty factor 0 if there
is at least one transit line following the edge and penalty factor 1 if
there are no transit lines at all following the edge.
Behavior in the case when a transit line is given is untouched.

This should improve routing results by preferring edges with
associated transit lines. This used to be the behavior before
some refactoring. Maybe it was broken unintentionally.

### CODE REVIEW

**Comment by aheld84** [comment]
Converted to draft since the solution suggested so far is not correct (see #18 )

**Comment by aheld84** [comment]
I have changed the PR such that it does not change the default behavior any more.

An additional penalty for edges without any transit lines can be added by setting `routing_no_lines_punish_fac` to a positive value in the config. The punishment is only active when no explicit transit line name/from/to was requested in the routing attrs.

**Review by patrickbr — APPROVED** [review]
Looks good.

**Comment by patrickbr** [comment]
Great, thank you very much. Merged.

**Pull request merged**
